### ISSUE TITLE
Put CSV to JSON conversion on website

### ISSUE THREAD

**Issue by nkalupahana** [FRC-7525/SimpleScope#2]
Right now, Python script is used. Move this to JS, and have it automatically convert on the website.

**Comment by gluecia** [comment]
Aiden already fixed this [here](https://github.com/FRC-7525/SimpleScope/commit/1d2dbfa2a1b613fb8348fcf919fc8e79b7e3491d#diff-0e09ec8bdbde7a5e8772d2663d2ad5f0c1b422aee222f84da23a1315252f3951)!
